// Locates a ComfyUI backend on the machine this app was installed on, and
// builds a launcher that starts the server alone. The listener only speaks to
// ComfyUI's HTTP/WebSocket API, so launching the Comfy Desktop GUI boots a
// whole Electron app for nothing.
//
// Kept free of Electron imports so it can be exercised by comfyui-detect.check.js.
//
// ponytail: Windows-only, and probes a fixed list of well-known install
// locations instead of walking the filesystem. Ceiling: an install in an
// unusual folder is not found — the settings UI still has a Browse… button,
// and a real scan could be added later behind an explicit "deep scan" action.

const path = require('path');
const fs = require('fs');

function readJsonSafe(file) {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8'));
  } catch (_) {
    return null;
  }
}

// A backend is only usable when both the interpreter and main.py are present.
function makeCandidate(kind, comfyDir, python, extraArgs) {
  if (!fs.existsSync(path.join(comfyDir, 'main.py')) || !fs.existsSync(python)) return null;
  return { kind, comfyDir, python, extraArgs: extraArgs || [] };
}

// 1. Comfy Desktop keeps an authoritative record of every local installation.
function detectDesktopInstall(appDataDir) {
  const desktopDir = path.join(appDataDir, 'Comfy Desktop');
  const installs = readJsonSafe(path.join(desktopDir, 'installations.json'));
  if (!Array.isArray(installs)) return null;

  const settings = readJsonSafe(path.join(desktopDir, 'settings.json')) || {};
  const sharedYaml = path.join(desktopDir, 'shared_model_paths.yaml');

  // Cloud entries carry no installPath; try the most recently launched first.
  const local = installs
    .filter(i => i && i.installPath && i.status === 'installed')
    .sort((a, b) => (b.lastLaunchedAt || 0) - (a.lastLaunchedAt || 0));

  for (const inst of local) {
    const comfyDir = path.join(inst.installPath, 'ComfyUI');
    const python = path.join(comfyDir, '.venv', 'Scripts', 'python.exe');

    // Reproduce Desktop's own configuration so the server behaves identically.
    const args = [];
    if (fs.existsSync(sharedYaml)) args.push('--extra-model-paths-config', sharedYaml);
    if (settings.outputDir) args.push('--output-directory', settings.outputDir);
    if (settings.inputDir) args.push('--input-directory', settings.inputDir);
    // Drop any --port Desktop saved; the listener supplies the port it dials.
    const saved = String(inst.launchArgs || '').split(/\s+/).filter(Boolean);
    for (let i = 0; i < saved.length; i++) {
      if (saved[i] === '--port') { i++; continue; }
      args.push(saved[i]);
    }

    const candidate = makeCandidate('desktop', comfyDir, python, args);
    if (candidate) return candidate;
  }
  return null;
}

// 2. Portable bundles and source checkouts, in the handful of places people
//    actually unpack them.
function detectPortableInstall(homeDir) {
  const roots = [];
  for (const drive of ['C:', 'D:', 'E:', 'F:']) {
    roots.push(`${drive}\\`, path.join(`${drive}\\`, 'AI'), path.join(`${drive}\\`, 'Program Files'));
  }
  if (homeDir) {
    roots.push(homeDir, path.join(homeDir, 'Documents'),
      path.join(homeDir, 'Desktop'), path.join(homeDir, 'Downloads'));
  }

  for (const root of roots) {
    if (!fs.existsSync(root)) continue;
    for (const name of ['ComfyUI_windows_portable', 'ComfyUI', '']) {
      const base = name ? path.join(root, name) : root;
      // Portable layout: <base>\python_embeded\python.exe + <base>\ComfyUI\main.py
      const portable = makeCandidate('portable', path.join(base, 'ComfyUI'),
        path.join(base, 'python_embeded', 'python.exe'));
      if (portable) return portable;
      // Source checkout with a venv sitting next to main.py
      const source = makeCandidate('source', base,
        path.join(base, '.venv', 'Scripts', 'python.exe'));
      if (source) return source;
    }
  }
  return null;
}

function detect({ appDataDir, homeDir }) {
  return detectDesktopInstall(appDataDir) || detectPortableInstall(homeDir);
}

// Returns the launcher pair as text so the contents can be asserted on without
// touching disk.
function buildLauncherScripts(candidate, port, batPath) {
  // Everything that is not a flag is a path or value and may contain spaces.
  const args = ['--port', String(port || 8188), ...candidate.extraArgs]
    .map(a => (a.startsWith('--') ? a : `"${a}"`))
    .join(' ');

  // No `pause` — the window is hidden, so a prompt would hang forever.
  const bat = [
    '@echo off',
    'REM Generated by ComfyUI Listener - starts the ComfyUI backend only.',
    'REM Safe to delete; it is rewritten every time detection runs.',
    `cd /d "${candidate.comfyDir}"`,
    `"${candidate.python}" main.py ${args}`,
    ''
  ].join('\r\n');

  // Run() window style 0 keeps the console completely hidden.
  const vbs = [
    "' Generated by ComfyUI Listener - runs the launcher with no visible window.",
    `CreateObject("WScript.Shell").Run """${batPath}""", 0, False`,
    ''
  ].join('\r\n');

  return { bat, vbs };
}

// userData stays writable when the app is packaged (unlike app.asar) and is
// per-user, so every install gets a launcher pointing at its own ComfyUI.
function writeLauncher(candidate, port, userDataDir) {
  const batPath = path.join(userDataDir, 'start_comfyui_server.bat');
  const vbsPath = path.join(userDataDir, 'start_comfyui_server.vbs');
  const { bat, vbs } = buildLauncherScripts(candidate, port, batPath);
  fs.writeFileSync(batPath, bat, 'utf8');
  fs.writeFileSync(vbsPath, vbs, 'utf8');
  return vbsPath;
}

module.exports = { detect, detectDesktopInstall, detectPortableInstall, buildLauncherScripts, writeLauncher };
